version: '3.9'

networks:
  inverse-network:
    name: inverse-network

volumes:
  open-webui: {}
  pipelines_cache: {}

services:
  open-webui:
    image: open-webui:latest
    build:
      context: .
      dockerfile: Dockerfile.inv
      args:
        USE_CUDA: "false"
        USE_OLLAMA: "false"
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    networks:
      - inverse-network
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ENABLE_OLLAMA_API=false
      - ENABLE_OPENAI_API=true
      - CORS_ALLOW_ORIGIN=https://chat.inverse.watch
      - USER_AGENT=InverseChat/1.0
      - WEBUI_SECURITY_HEADERS=true
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/chat.inverse.watch/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/chat.inverse.watch/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    depends_on:
      - open-webui
    restart: unless-stopped
    networks:
      - inverse-network

  pipelines:
    image: pipelines:latest
    build:
      context: ./pipelines
      dockerfile: Dockerfile
      args:
        - MINIMUM_BUILD=false
        - USE_CUDA=false
        - USE_CUDA_VER=cpu
    ports:
      - "9099:9099"
    volumes:
      - ./pipelines:/app/pipelines
      - pipelines_cache:/root/.cache
    environment:
      - ENV=prod
      - HOST=0.0.0.0
      - PORT=9099
    working_dir: /app/pipelines
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - inverse-network
