version: '3.9'

services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_CUDA: "false"
        USE_OLLAMA: "false"
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ENABLE_OLLAMA_API=false
      - ENABLE_OPENAI_API=true
      - CORS_ALLOW_ORIGIN=https://chat.inverse.watch
      - USER_AGENT=InverseChat/1.0
      - WEBUI_SECURITY_HEADERS=true
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/chat.inverse.watch/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/chat.inverse.watch/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    depends_on:
      - open-webui
    restart: unless-stopped

volumes:
  open-webui: {}
